### PR TITLE
chore(project): cleanup

### PR DESCRIPTION
**Pull request by alex1431999**
# Purpose
This PR does some cleanup work in order to get the Repository up to speed again.

## Changes
- README updates
- Dependency updates

## Note
- We couldn't upgrade `chart.js` to its next major release since it was incompatible with the latest version of `vue-chart.js`.
- We didn't upgrade `eslint` since there were many breaking changes and the linting is fine as it is.

### CODE REVIEW

**Comment by six-edge** [comment]
@alex1431999 thanks for the PR. Could you see if upgrading `chart.js` would be possible? It shouldn't be to much effort. 
It would be great to migrate it to the latest version to keep up to date and take advantages of sec updates.

**Comment by alex1431999** [comment]
> @alex1431999 thanks for the PR. Could you see if upgrading `chart.js` would be possible? It shouldn't be to much effort. It would be great to migrate it to the latest version to keep up to date and take advantages of sec updates.

As mentioned in the PR description, it is not possible to upgrade `chart.js`.

The reason being, that `vue-chart.js` is depending on `chart.js` as an external and it is assuming a version that is incompatible with the new major release of `chart.js`.

`chart.js` changed their exports in the major release and `vue-chart.js` in its latest version is still assuming the former export structure.

**Comment by alex1431999** [comment]
@six-edge am I okay merging the PR?

**Review by six-edge-ops — APPROVED** [review]
Go for it!

**Pull request merged**
